#GCCFLAGS=-g -ansi -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -pedantic
#CXX = g++
#CXXFLAGS = $(GCCFLAGS)
#LDFLAGS = -lm


############################
# GCC settings (special)
############################
#GCCFLAGS=-g -ansi -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -pedantic
#GCCDIR=/local/gcc/rundir
#CXX =  $(GCCDIR)/bin/g++
#CXXFLAGS = $(GCCFLAGS)
#LDFLAGS = -L$(LIBCPPDIR) -Wl,--rpath -Wl,$(LIBCPPDIR) -lm

epydoc = Builder(action = 'epydoc --html --name Pyx12 --no-frames -o ../doc/epydoc .', 
    src_suffix = '.py',
    suffix = '.html')
#/usr/local/lib/gcc/i386-portbld-freebsd4.10/3.4.4/include/c++/
env = Environment(CC = 'g++', CCFLAGS = '-g -O2 -W -Wall -ansi -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -pedantic')
env.Append(BUILDERS = {'Doc' : epydoc})
#Program(['test1.cxx', 'segment.cxx', 'errors.cxx'])
#includes = Dir(['.', '/usr/include', 'usr/local/include'])
env.Program('test1', 'test1.cxx', LIBS=['pyx12'], LIBPATH=['.', '/usr/lib', '/usr/local/lib'])
env.Doc('../doc/epydoc/index.html')
#Object('x12file.cxx')
#Object('segment.cxx')
#Program('program', ['main.c', 'file1.c', 'file2.c'])
env.Library('pyx12', ['segment.cxx', 'errors.cxx'])
#StaticLibrary('foo', ['f1.c', 'f2.c', 'f3.c'])
#SharedLibrary('pyx12', ['segment.cxx', 'errors.cxx'])
