#! /usr/bin/env /usr/local/bin/python
# script to validate a X12N batch transaction set  and convert it into an XML document
#
#    $Id$
#    This file is part of the pyX12 project.
#
#    Copyright (c) 2001-2004 Kalamazoo Community Mental Health Services,
#                John Holland <jholland@kazoocmh.org> <john@zoner.org>
#
#    All rights reserved.
#
#        Redistribution and use in source and binary forms, with or without modification, 
#        are permitted provided that the following conditions are met:
#
#        1. Redistributions of source code must retain the above copyright notice, this list 
#           of conditions and the following disclaimer. 
#        
#        2. Redistributions in binary form must reproduce the above copyright notice, this 
#           list of conditions and the following disclaimer in the documentation and/or other 
#           materials provided with the distribution. 
#        
#        3. The name of the author may not be used to endorse or promote products derived 
#           from this software without specific prior written permission. 
#
#        THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED 
#        WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
#        MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO 
#        EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
#        EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
#        OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
#        INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
#        CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
#        ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
#        THE POSSIBILITY OF SUCH DAMAGE.

# THIS IS PRE-ALPHA CODE.  IT DOES NOT WORK. 

"""
Parse a ANSI X12N data file.
Validate against a map and codeset values.
Create a XML document based on the data file
"""

import os, os.path
import sys
import logging
from types import *
import pdb
#import profile

# Intrapackage imports
#import error_handler
import error_997
import error_debug
import error_html
#from errors import *
from pyx12 import x12n_document
#from utils import *
from params import params

__author__  = "John Holland <jholland@kazoocmh.org> <john@zoner.org>"
__status__  = "beta"
__version__ = "0.3.0.0"
__date__    = "10/1/2003"

def usage():
    sys.stdout.write('usage: x12lint source_file [target_997 [target_html]]\n')
    
def main():
    """
    Set up environment for processing
    """
    import getopt
    param = params()
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'qv')
    except getopt.error, msg:
        sys.stdout.write('usage: pyx12.py source_file [target_997 [target_html]]\n')
        raise
        sys.exit(2)
    logger = logging.getLogger('pyx12')
    hdlr = logging.FileHandler('./run.log')
    stderr_hdlr = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(module)s %(lineno)d %(message)s')
    hdlr.setFormatter(formatter)
    stderr_hdlr.setFormatter(formatter)
    logger.addHandler(hdlr) 
    logger.addHandler(stderr_hdlr)
    logger.setLevel(logging.INFO)

    target_html = ''
    target_997 = ''
    for o, a in opts:
        if o == '-v': logger.setLevel(logging.DEBUG)
        if o == '-q': logger.setLevel(logging.ERROR)
        if o == '-c': param.set_param('charset', a)
        #if o == '-H': target_html = a
        #if o == '-E': target_997 = a

    try:
        #print args
        if args:
            src_filename = args[0]
            fd_src = open(src_filename, 'U')
            if len(args) > 1:
                target_997 = args[1]
                if target_997 == '-':
                    fd_997 = sys.stdout
                else:
                    fd_997 = open(target_997, 'w')
            else:
                target_997 = os.path.splitext(src_filename)[0] + '.997.txt'
                fd_997 = open(target_997, 'w')
            if len(args) > 2:
                target_html = args[1]
                if target_html == '-':
                    fd_html = sys.stdout
                else:
                    fd_html = open(target_html, 'w')
            else:
                target_html = os.path.splitext(src_filename)[0] + '.html'
                fd_html = open(target_html, 'w')
    except:
        logger.error('Could not open files')
        usage()
        sys.exit(2)

    try:
        x12n_document(param, fd_src, fd_997, fd_html)
    except KeyboardInterrupt:
        print "\n[interrupt]"
    return True

#profile.run('x12n_document(src_filename)', 'pyx12.prof')
if __name__ == '__main__':
    sys.exit(not main())

