#boost:
#Don't forget to add -pthread to your linker options when linking your code.
#You have built the Boost.Python library. You have to add the following
#options when building your own code:
#Compiler options:
#   -I/usr/local/include/python2.4 -I/usr/local/include
#Linker options:
#   -L/usr/local/lib/python2.4 -L/usr/local/lib -lboost_python -lpython2.4

env = Environment(CC = 'g++', CCFLAGS = '-g -O2 -W -Wall -ansi -Wwrite-strings -pedantic')
env.Replace(CPPPATH = ['.', '../pyx12', '/usr/include', '/usr/local/include', \
    '/usr/local/include/python2.4'])
env.Replace(LIBS = ['pyx12', 'boost_unit_test_framework', 'boost_python', 'python2.4']) #, 'libc_r'])
env.Replace(LIBPATH = ['.', '../pyx12', '/usr/lib', '/usr/local/lib', '/usr/local/lib/python2.4'])

env.Program('t1', 't1.cxx', LINKFLAGS='-pthread')
#env.Program('test_csegment', 'test_csegment.cxx') #, LINKFLAGS='-pthread')
